defaults: &defaults
  app_id: '2LRH0UGPXER4KLVDBCOHZUNKKWWCM5JI0B2F05IDFUEREUMD'
  app_secret: 'M4EK4OH2FMKH0WNFJYDPL2GWNAF1AOCTZ4YE1XFE22OQXN0H'
  yahoo_id: '0yJmk9cUNjYUg0RWhVOG1aJmQ9WVdrOVNUZEdkMjFrTXpJbWNHbzlNVEV4TVRJd05UWXkmcz1jb25zdW1lcnNlY3JldCZ4PWI'
  foursquare_api: '2LRH0UGPXER4KLVDBCOHZUNKKWWCM5JI0B2F05IDFUEREUMD' 
  foursquare_secret: 'M4EK4OH2FMKH0WNFJYDPL2GWNAF1AOCTZ4YE1XFE22OQXN0H'
  yelp: 'GanonVA_293b8gzCHFgHdQ'
  project_name: 'Powerlisting'
  tracker: 'Affiliate'
  status: 'New'  
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
#citygrid: &cities
# app_id: '2LRH0UGPXER4KLVDBCOHZUNKKWWCM5JI0B2F05IDFUEREUMD'
#development:
 # <<: *cities
